"""AOS-RESUME1A/#1431: execution-checkpoint record, construction, store, and resume planner."""

from .construction import (
    ACCEPTANCE_CRITERIA_DIGEST_DOMAIN,
    DEPENDENCY_FINGERPRINT_DOMAIN,
    ENVIRONMENT_FINGERPRINT_DOMAIN,
    GOVERNANCE_CONTRACT_DIGEST_DOMAIN,
    WORKTREE_FINGERPRINT_DOMAIN,
    AcceptanceCriteriaEvidence,
    CanonicalExecutionEvidence,
    CheckpointConstructionError,
    DependencyEvidence,
    DependencyManifestEvidence,
    EnvironmentEvidence,
    GovernanceContractEvidence,
    GovernanceDocumentEvidence,
    StageObservation,
    WorktreeEvidence,
    construct_execution_checkpoint,
    derive_acceptance_criteria_digest,
    derive_dependency_fingerprint,
    derive_environment_fingerprint,
    derive_governance_contract_digest,
    derive_worktree_fingerprint,
    select_highest_truthful_stage,
)
from .identity import (
    CHECKPOINT_ID_DOMAIN,
    REUSE_KEY_DOMAIN,
    canonical_json_bytes,
    compute_checkpoint_id,
    compute_reuse_key,
    compute_resume_plan_id,
    domain_digest,
)
from .invalidation import (
    ALL_STAGES,
    EVIDENCE_HASH_CI_RESULT,
    EVIDENCE_HASH_EXTERNAL_LIFECYCLE,
    EVIDENCE_HASH_PR_HEAD_SHA,
    EVIDENCE_HASH_REVIEW_STATE,
    STAGE_INVALIDATION_TRIGGERS,
    TRIGGER_STAGES,
    BindingSnapshot,
    InvalidationTrigger,
    binding_snapshot_from_checkpoint,
    detect_triggers,
    is_stage_invalidated,
)
from .models import (
    CANONICAL_STAGE_ORDER,
    CHECKPOINT_SCHEMA_NAME,
    CHECKPOINT_SCHEMA_VERSION,
    LIFECYCLE_STAGE_ORDER,
    STAGE_AUTO_RESUME_SAFE_MAP,
    STAGE_IDEMPOTENT_MAP,
    STAGE_KIND_MAP,
    STAGE_LIFECYCLE_MAP,
    CheckpointStage,
    ExecutionCheckpoint,
    InvalidationState,
    LifecycleState,
    StageKind,
    StageStatus,
    WorktreeRole,
    checkpoint_from_dict,
    deserialize_checkpoint,
    serialize_checkpoint,
)
from .mutation_intent import MUTATION_INTENT_DOMAIN, compute_mutation_intent_id
from .resume_planner import (
    CHECKPOINT_STAGE_AUTHORITY_FIELD,
    RESUME_PLAN_SCHEMA_NAME,
    RESUME_PLAN_SCHEMA_VERSION,
    AuthorityCeiling,
    ResumePlan,
    StageClassification,
    StageDecision,
    authority_ceiling_from_decision,
    authority_permits_stage,
    plan_resume,
)
from .store import (
    MAX_BYTES_PER_ISSUE,
    MAX_RECORDS_PER_ISSUE,
    AppendOutcome,
    CheckpointStoreCapacityExceeded,
    CheckpointStoreIntegrityConflict,
    CheckpointStoreUnavailable,
    LoadedCheckpoint,
    LoadResult,
    QuarantinedEntry,
    append_checkpoint,
    issue_store_dir,
    load_checkpoints,
    read_head,
    retention_cutoff_epoch_seconds,
    store_is_available,
    write_quarantine_record,
)

__all__ = [
    "ACCEPTANCE_CRITERIA_DIGEST_DOMAIN", "ALL_STAGES", "AcceptanceCriteriaEvidence",
    "append_checkpoint", "AppendOutcome", "authority_ceiling_from_decision",
    "authority_permits_stage", "AuthorityCeiling", "binding_snapshot_from_checkpoint",
    "BindingSnapshot", "canonical_json_bytes", "CANONICAL_STAGE_ORDER",
    "CanonicalExecutionEvidence", "checkpoint_from_dict", "CHECKPOINT_ID_DOMAIN",
    "CHECKPOINT_SCHEMA_NAME", "CHECKPOINT_SCHEMA_VERSION", "CHECKPOINT_STAGE_AUTHORITY_FIELD",
    "CheckpointConstructionError", "CheckpointStage", "CheckpointStoreCapacityExceeded",
    "CheckpointStoreIntegrityConflict", "CheckpointStoreUnavailable", "compute_checkpoint_id",
    "compute_mutation_intent_id", "compute_resume_plan_id", "compute_reuse_key",
    "construct_execution_checkpoint", "DEPENDENCY_FINGERPRINT_DOMAIN", "DependencyEvidence",
    "DependencyManifestEvidence", "deserialize_checkpoint", "detect_triggers", "domain_digest",
    "derive_acceptance_criteria_digest", "derive_dependency_fingerprint",
    "derive_environment_fingerprint", "derive_governance_contract_digest",
    "derive_worktree_fingerprint", "ENVIRONMENT_FINGERPRINT_DOMAIN", "EnvironmentEvidence",
    "EVIDENCE_HASH_CI_RESULT", "EVIDENCE_HASH_EXTERNAL_LIFECYCLE", "EVIDENCE_HASH_PR_HEAD_SHA",
    "EVIDENCE_HASH_REVIEW_STATE", "ExecutionCheckpoint", "GOVERNANCE_CONTRACT_DIGEST_DOMAIN",
    "GovernanceContractEvidence", "GovernanceDocumentEvidence", "InvalidationState",
    "InvalidationTrigger", "is_stage_invalidated", "issue_store_dir", "LIFECYCLE_STAGE_ORDER",
    "LifecycleState", "load_checkpoints", "LoadedCheckpoint", "LoadResult", "MAX_BYTES_PER_ISSUE",
    "MAX_RECORDS_PER_ISSUE", "MUTATION_INTENT_DOMAIN", "plan_resume", "QuarantinedEntry",
    "read_head", "RESUME_PLAN_SCHEMA_NAME", "RESUME_PLAN_SCHEMA_VERSION", "ResumePlan",
    "retention_cutoff_epoch_seconds", "REUSE_KEY_DOMAIN", "select_highest_truthful_stage",
    "serialize_checkpoint", "STAGE_AUTO_RESUME_SAFE_MAP", "STAGE_IDEMPOTENT_MAP",
    "STAGE_INVALIDATION_TRIGGERS", "STAGE_KIND_MAP", "STAGE_LIFECYCLE_MAP",
    "StageClassification", "StageDecision", "StageKind", "StageObservation", "StageStatus",
    "store_is_available", "TRIGGER_STAGES", "WORKTREE_FINGERPRINT_DOMAIN", "WorktreeEvidence",
    "WorktreeRole", "write_quarantine_record",
]
