"""Offline issue drafting, validation, and explicit GitHub issue creation adapters."""

from .checker import evaluate_issue_labels
from .draft import (
    IssueDraftInput,
    IssueDraftResult,
    build_issue_draft,
    draft_result_to_dict,
    render_draft_preview,
)
from .issue_create import (
    ConfirmationProvider,
    GhCapabilities,
    GhRunner,
    GitHubRepositoryTarget,
    IssueCreateAdapterResult,
    IssueCreateCommandPlan,
    IssueCreateConfirmation,
    IssueCreateExitCode,
    IssueCreateProcessResult,
    IssueCreateReasonCode,
    IssueCreateRequest,
    MutationState,
    SubprocessGhRunner,
    build_issue_create_argv,
    build_operation_fingerprint,
    execute_issue_creation,
    issue_create_result_to_dict,
    plan_issue_creation,
    render_issue_create_result,
    sanitize_diagnostic_text,
)
from .planner import LabelApplicationPlan, plan_label_application
from .pr_branch_refresh import (
    BranchRefreshMutationResult,
    BranchRefreshValidationResult,
    PullRequestBranchRefreshProvider,
    PullRequestBranchRefreshRequest,
    PullRequestBranchRefreshResult,
    PullRequestBranchSnapshot,
    refresh_pull_request_branch,
)
from .pr_branch_refresh_provider import (
    ProductionPullRequestBranchRefreshProvider,
    PullRequestBranchRefreshBackingProvider,
)
from .pr_lifecycle import (
    PullRequestLifecycleReconciliationResult,
    lifecycle_invocation_reasons,
    reconcile_pull_request_lifecycle,
)
from .pr_reconciler import (
    BatchPullRequestLabelReconciliationResult,
    LivePullRequestSnapshot,
    PullRequestLabelProvider,
    PullRequestLabelReconciliationResult,
    reconcile_pull_request_batch,
    reconcile_pull_request_labels,
)
from .validation import (
    DraftExitCode,
    DraftReasonCode,
    IssueDraftValidationResult,
    render_validation_preview,
    validate_issue_draft,
    validation_exit_code,
    validation_result_to_dict,
)

__all__ = [
    "BatchPullRequestLabelReconciliationResult",
    "BranchRefreshMutationResult",
    "BranchRefreshValidationResult",
    "ConfirmationProvider",
    "DraftExitCode",
    "DraftReasonCode",
    "GhCapabilities",
    "GhRunner",
    "GitHubRepositoryTarget",
    "IssueCreateAdapterResult",
    "IssueCreateCommandPlan",
    "IssueCreateConfirmation",
    "IssueCreateExitCode",
    "IssueCreateProcessResult",
    "IssueCreateReasonCode",
    "IssueCreateRequest",
    "IssueDraftInput",
    "IssueDraftResult",
    "IssueDraftValidationResult",
    "LabelApplicationPlan",
    "LivePullRequestSnapshot",
    "MutationState",
    "ProductionPullRequestBranchRefreshProvider",
    "PullRequestBranchRefreshBackingProvider",
    "PullRequestBranchRefreshProvider",
    "PullRequestBranchRefreshRequest",
    "PullRequestBranchRefreshResult",
    "PullRequestBranchSnapshot",
    "PullRequestLabelProvider",
    "PullRequestLabelReconciliationResult",
    "PullRequestLifecycleReconciliationResult",
    "SubprocessGhRunner",
    "build_issue_create_argv",
    "build_issue_draft",
    "build_operation_fingerprint",
    "draft_result_to_dict",
    "evaluate_issue_labels",
    "execute_issue_creation",
    "issue_create_result_to_dict",
    "lifecycle_invocation_reasons",
    "plan_issue_creation",
    "plan_label_application",
    "reconcile_pull_request_batch",
    "reconcile_pull_request_labels",
    "reconcile_pull_request_lifecycle",
    "refresh_pull_request_branch",
    "render_draft_preview",
    "render_issue_create_result",
    "render_validation_preview",
    "sanitize_diagnostic_text",
    "validate_issue_draft",
    "validation_exit_code",
    "validation_result_to_dict",
]
