"""Immutable, read-only Agent OS execution capability evidence."""

from .approved_projection import (
    GOVERNED_PROJECTION_EVIDENCE_SCHEMA_VERSION,
    GovernedProjectionEvidenceResult,
    consume_approved_projection_evidence,
)
from .dependencies import (
    DependencyArtifactIdentity,
    DependencyCacheState,
    DependencyEcosystem,
    DependencyInstallMode,
    DependencyPreparationStatus,
    DependencyReadinessEvidence,
    LocalProjectRequirement,
    QualificationOnlyDependencyPin,
    ReproducibilityLevel,
    RequiredEnvironmentSpec,
    dependency_readiness_evidence_payload,
    required_environment_spec_payload,
)
from .models import (
    CAPABILITY_EVIDENCE_SCHEMA_NAME,
    CAPABILITY_EVIDENCE_SCHEMA_VERSION,
    CapabilityEvidence,
    CapabilityEvidenceEnvelope,
    CapabilityStatus,
    EvidenceStrength,
    ExecutionDecision,
    RepositoryEvidenceType,
    RepositoryIdentity,
    RepositoryStateEvidence,
    RepositoryStateValidationResult,
    WorktreeState,
)
from .repository_state import (
    reconstruct_repository_state_validation_result,
    serialize_repository_state_validation_result,
    validate_capability_evidence,
    validate_repository_state_evidence,
)
from .serialization import serialize_capability_evidence

__all__ = [
    "CAPABILITY_EVIDENCE_SCHEMA_NAME",
    "CAPABILITY_EVIDENCE_SCHEMA_VERSION",
    "GOVERNED_PROJECTION_EVIDENCE_SCHEMA_VERSION",
    "CapabilityEvidence",
    "CapabilityEvidenceEnvelope",
    "CapabilityStatus",
    "DependencyArtifactIdentity",
    "DependencyCacheState",
    "DependencyEcosystem",
    "DependencyInstallMode",
    "DependencyPreparationStatus",
    "DependencyReadinessEvidence",
    "EvidenceStrength",
    "ExecutionDecision",
    "GovernedProjectionEvidenceResult",
    "LocalProjectRequirement",
    "QualificationOnlyDependencyPin",
    "RepositoryEvidenceType",
    "RepositoryIdentity",
    "RepositoryStateEvidence",
    "RepositoryStateValidationResult",
    "ReproducibilityLevel",
    "RequiredEnvironmentSpec",
    "WorktreeState",
    "consume_approved_projection_evidence",
    "dependency_readiness_evidence_payload",
    "reconstruct_repository_state_validation_result",
    "required_environment_spec_payload",
    "serialize_capability_evidence",
    "serialize_repository_state_validation_result",
    "validate_capability_evidence",
    "validate_repository_state_evidence",
]
